# Script-mode helper for transcriptor_embed_assets(). Reads every file under ASSET_ROOT
# and writes a single C++ translation unit holding them as byte arrays.
#
# Invoked as: cmake -DASSET_ROOT=... -DASSET_OUT=... -P embed_assets_run.cmake

if(NOT ASSET_ROOT OR NOT ASSET_OUT)
    message(FATAL_ERROR "ASSET_ROOT and ASSET_OUT are required")
endif()

file(GLOB_RECURSE _files RELATIVE "${ASSET_ROOT}" "${ASSET_ROOT}/*")
list(FILTER _files EXCLUDE REGEX "(^|/)\\.")
list(SORT _files)

set(_body "// Generated by embed_assets_run.cmake -- do not edit.\n")
string(APPEND _body "#include \"app/assets.h\"\n\n")
string(APPEND _body "namespace {\n")

set(_index "")
set(_n 0)

foreach(_f IN LISTS _files)
    math(EXPR _n "${_n}+1")
    set(_sym "a${_n}")

    file(READ "${ASSET_ROOT}/${_f}" _hex HEX)
    string(LENGTH "${_hex}" _hexlen)
    math(EXPR _len "${_hexlen}/2")

    # "6162" -> "0x61,0x62," with a newline every 16 bytes for readable output.
    string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "((0x..,){16})" "\\1\n" _bytes "${_bytes}")

    string(APPEND _body "const unsigned char ${_sym}[] = {\n${_bytes}0x00};\n")

    # Content type from the extension.
    get_filename_component(_ext "${_f}" LAST_EXT)
    string(TOLOWER "${_ext}" _ext)
    if(_ext STREQUAL ".html")
        set(_mime "text/html; charset=utf-8")
    elseif(_ext STREQUAL ".js")
        set(_mime "application/javascript; charset=utf-8")
    elseif(_ext STREQUAL ".css")
        set(_mime "text/css; charset=utf-8")
    elseif(_ext STREQUAL ".woff2")
        set(_mime "font/woff2")
    elseif(_ext STREQUAL ".woff")
        set(_mime "font/woff")
    elseif(_ext STREQUAL ".svg")
        set(_mime "image/svg+xml")
    elseif(_ext STREQUAL ".png")
        set(_mime "image/png")
    elseif(_ext STREQUAL ".ico")
        set(_mime "image/x-icon")
    elseif(_ext STREQUAL ".json")
        set(_mime "application/json; charset=utf-8")
    else()
        set(_mime "application/octet-stream")
    endif()

    string(APPEND _index
        "    {\"${_f}\", reinterpret_cast<const char*>(${_sym}), ${_len}, \"${_mime}\"},\n")
endforeach()

string(APPEND _body "\nconst transcriptor::Asset kAssets[] = {\n${_index}};\n")
string(APPEND _body "const std::size_t kAssetCount = sizeof(kAssets)/sizeof(kAssets[0]);\n")
string(APPEND _body "}  // namespace\n\n")

string(APPEND _body
"namespace transcriptor {

const Asset* find_asset(const std::string& path) {
    for (std::size_t i = 0; i < kAssetCount; ++i) {
        if (path == kAssets[i].path) return &kAssets[i];
    }
    return nullptr;
}

std::vector<const Asset*> all_assets() {
    std::vector<const Asset*> out;
    out.reserve(kAssetCount);
    for (std::size_t i = 0; i < kAssetCount; ++i) out.push_back(&kAssets[i]);
    return out;
}

}  // namespace transcriptor
")

file(WRITE "${ASSET_OUT}" "${_body}")
message(STATUS "Embedded ${_n} asset(s) -> ${ASSET_OUT}")
