name: win-msvc

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', 'LICENSE', '.gitignore']
  pull_request:
    paths-ignore: ['**.md', 'LICENSE', '.gitignore']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      preset: win-msvc
      os: windows-2022
